### ISSUE TITLE
python3 support?

### ISSUE THREAD

**Issue by jperrigo-aiteam** [sideeffects/HoudiniLiveLink#5]
Just checking if this is currently intended to work with H19/python 3?

When I try to start server from either 18.5/19 python 3 build I get the following error:

Traceback (most recent call last):
  File "Sop/ue4_livelink/start_server", line 1, in <module>
  File "Sop/ue4_livelink, PythonModule", line 88, in start_server
  File "Sop/ue4_livelink, PythonModule", line 71, in outputPlaybarEvent
TypeError: a bytes-like object is required, not 'str'

**Comment by jperrigo-aiteam** [comment]
this has now been fixed, thanks!
