### ISSUE TITLE
Traceback when trying to start server

### ISSUE THREAD

**Issue by vfxbyjohn** [sideeffects/HoudiniLiveLink#7]
Whenever I try Start Server I get the following error:

```
Traceback (most recent call last):
  File "Sop/ue4_livelink/start_server", line 1, in <module>
  File "Sop/ue4_livelink, PythonModule", line 88, in start_server
  File "Sop/ue4_livelink, PythonModule", line 71, in outputPlaybarEvent
TypeError: a bytes-like object is required, not 'str'
```

This is with the 1.2/UE5 build, tried with H19 and H19.5 under Windows 10, same error, any insights as to what might be causing this?

**Comment by vfxbyjohn** [comment]
If I switch to the 1.2/UE 4.27 build that was released in Nov 2021 that works, but the latest build from July 2022 for UE5 has the above error

**Comment by OptimisticMonkey** [comment]
Thanks John - Fix with update in progress

**Comment by Himanshu9152704239** [comment]
@OptimisticMonkey 
waiting for update 

please add support for complete Livelink features
