### ISSUE TITLE
support for unreal 5.2 

### ISSUE THREAD

**Issue by talal-jpg** [sideeffects/HoudiniLiveLink#8]
is there a new way to live link kinefx to unreal ? just asking bcz there isnt even a version fr 5.1

**Comment by talal-jpg** [comment]
the plugin gets installed without any problems even in unreal 5.2
 but the HDA is not working in houdini 
Traceback (most recent call last):
  File "Sop/ue4_livelink/start_server", line 1, in <module>
  File "Sop/ue4_livelink, PythonModule", line 88, in start_server
  File "Sop/ue4_livelink, PythonModule", line 71, in outputPlaybarEvent
TypeError: a bytes-like object is required, not 'str'
